name = "logicalmechanism/assist"
version = "0.5.0"
compiler = "v1.0.31-alpha"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken Assist Library"

[repository]
user = "logicalmechanism"
project = "assist"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"
